excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://norskcasino.github.io
name: Norsk Casinoguide Blog
description: Informasjon om casino på nett, poker og bingo. Vi har testet over 500 forskjellige spillesteder og skrevet om mer enn 150 ulike spill. Nyheter, artikler, regler og tips om spilleplasser og casinospill. 
author: norskcasino
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 